spring:
  datasource:
    url: jdbc:h2:mem:razziesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  jackson:
    serialization:
      indent-output: true

app:
  csv:
    localizacao: classpath:data/movielist.csv

logging:
  level:
    com.outsera.razzies.loader.CsvMovieLoader: INFO
    com.outsera.razzies.service.ProducerAwardIntervalService: INFO
